// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: exercisepb/hub.proto

package exercisepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ExerciseService_NewExercise_FullMethodName                    = "/exercisepb.ExerciseService/NewExercise"
	ExerciseService_AnswerExercise_FullMethodName                 = "/exercisepb.ExerciseService/AnswerExercise"
	ExerciseService_UpdateExerciseAudio_FullMethodName            = "/exercisepb.ExerciseService/UpdateExerciseAudio"
	ExerciseService_GetUserExercises_FullMethodName               = "/exercisepb.ExerciseService/GetUserExercises"
	ExerciseService_GetUserReadyForReviewExercises_FullMethodName = "/exercisepb.ExerciseService/GetUserReadyForReviewExercises"
	ExerciseService_ChangeExerciseFavorite_FullMethodName         = "/exercisepb.ExerciseService/ChangeExerciseFavorite"
	ExerciseService_GetUserFavoriteExercises_FullMethodName       = "/exercisepb.ExerciseService/GetUserFavoriteExercises"
	ExerciseService_GetUserStats_FullMethodName                   = "/exercisepb.ExerciseService/GetUserStats"
	ExerciseService_GetExerciseCollections_FullMethodName         = "/exercisepb.ExerciseService/GetExerciseCollections"
	ExerciseService_GetUserRecentExercisesChart_FullMethodName    = "/exercisepb.ExerciseService/GetUserRecentExercisesChart"
)

// ExerciseServiceClient is the client API for ExerciseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExerciseServiceClient interface {
	NewExercise(ctx context.Context, in *NewExerciseRequest, opts ...grpc.CallOption) (*NewExerciseResponse, error)
	AnswerExercise(ctx context.Context, in *AnswerExerciseRequest, opts ...grpc.CallOption) (*AnswerExerciseResponse, error)
	UpdateExerciseAudio(ctx context.Context, in *UpdateExerciseAudioRequest, opts ...grpc.CallOption) (*UpdateExerciseAudioResponse, error)
	GetUserExercises(ctx context.Context, in *GetUserExercisesRequest, opts ...grpc.CallOption) (*GetUserExercisesResponse, error)
	GetUserReadyForReviewExercises(ctx context.Context, in *GetUserReadyForReviewExercisesRequest, opts ...grpc.CallOption) (*GetUserReadyForReviewExercisesResponse, error)
	ChangeExerciseFavorite(ctx context.Context, in *ChangeExerciseFavoriteRequest, opts ...grpc.CallOption) (*ChangeExerciseFavoriteResponse, error)
	GetUserFavoriteExercises(ctx context.Context, in *GetUserFavoriteExercisesRequest, opts ...grpc.CallOption) (*GetUserFavoriteExercisesResponse, error)
	GetUserStats(ctx context.Context, in *GetUserStatsRequest, opts ...grpc.CallOption) (*GetUserStatsResponse, error)
	GetExerciseCollections(ctx context.Context, in *GetExerciseCollectionsRequest, opts ...grpc.CallOption) (*GetExerciseCollectionsResponse, error)
	GetUserRecentExercisesChart(ctx context.Context, in *GetUserRecentExercisesChartRequest, opts ...grpc.CallOption) (*GetUserRecentExercisesChartResponse, error)
}

type exerciseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExerciseServiceClient(cc grpc.ClientConnInterface) ExerciseServiceClient {
	return &exerciseServiceClient{cc}
}

func (c *exerciseServiceClient) NewExercise(ctx context.Context, in *NewExerciseRequest, opts ...grpc.CallOption) (*NewExerciseResponse, error) {
	out := new(NewExerciseResponse)
	err := c.cc.Invoke(ctx, ExerciseService_NewExercise_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) AnswerExercise(ctx context.Context, in *AnswerExerciseRequest, opts ...grpc.CallOption) (*AnswerExerciseResponse, error) {
	out := new(AnswerExerciseResponse)
	err := c.cc.Invoke(ctx, ExerciseService_AnswerExercise_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) UpdateExerciseAudio(ctx context.Context, in *UpdateExerciseAudioRequest, opts ...grpc.CallOption) (*UpdateExerciseAudioResponse, error) {
	out := new(UpdateExerciseAudioResponse)
	err := c.cc.Invoke(ctx, ExerciseService_UpdateExerciseAudio_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetUserExercises(ctx context.Context, in *GetUserExercisesRequest, opts ...grpc.CallOption) (*GetUserExercisesResponse, error) {
	out := new(GetUserExercisesResponse)
	err := c.cc.Invoke(ctx, ExerciseService_GetUserExercises_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetUserReadyForReviewExercises(ctx context.Context, in *GetUserReadyForReviewExercisesRequest, opts ...grpc.CallOption) (*GetUserReadyForReviewExercisesResponse, error) {
	out := new(GetUserReadyForReviewExercisesResponse)
	err := c.cc.Invoke(ctx, ExerciseService_GetUserReadyForReviewExercises_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) ChangeExerciseFavorite(ctx context.Context, in *ChangeExerciseFavoriteRequest, opts ...grpc.CallOption) (*ChangeExerciseFavoriteResponse, error) {
	out := new(ChangeExerciseFavoriteResponse)
	err := c.cc.Invoke(ctx, ExerciseService_ChangeExerciseFavorite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetUserFavoriteExercises(ctx context.Context, in *GetUserFavoriteExercisesRequest, opts ...grpc.CallOption) (*GetUserFavoriteExercisesResponse, error) {
	out := new(GetUserFavoriteExercisesResponse)
	err := c.cc.Invoke(ctx, ExerciseService_GetUserFavoriteExercises_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetUserStats(ctx context.Context, in *GetUserStatsRequest, opts ...grpc.CallOption) (*GetUserStatsResponse, error) {
	out := new(GetUserStatsResponse)
	err := c.cc.Invoke(ctx, ExerciseService_GetUserStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetExerciseCollections(ctx context.Context, in *GetExerciseCollectionsRequest, opts ...grpc.CallOption) (*GetExerciseCollectionsResponse, error) {
	out := new(GetExerciseCollectionsResponse)
	err := c.cc.Invoke(ctx, ExerciseService_GetExerciseCollections_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exerciseServiceClient) GetUserRecentExercisesChart(ctx context.Context, in *GetUserRecentExercisesChartRequest, opts ...grpc.CallOption) (*GetUserRecentExercisesChartResponse, error) {
	out := new(GetUserRecentExercisesChartResponse)
	err := c.cc.Invoke(ctx, ExerciseService_GetUserRecentExercisesChart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExerciseServiceServer is the server API for ExerciseService service.
// All implementations should embed UnimplementedExerciseServiceServer
// for forward compatibility
type ExerciseServiceServer interface {
	NewExercise(context.Context, *NewExerciseRequest) (*NewExerciseResponse, error)
	AnswerExercise(context.Context, *AnswerExerciseRequest) (*AnswerExerciseResponse, error)
	UpdateExerciseAudio(context.Context, *UpdateExerciseAudioRequest) (*UpdateExerciseAudioResponse, error)
	GetUserExercises(context.Context, *GetUserExercisesRequest) (*GetUserExercisesResponse, error)
	GetUserReadyForReviewExercises(context.Context, *GetUserReadyForReviewExercisesRequest) (*GetUserReadyForReviewExercisesResponse, error)
	ChangeExerciseFavorite(context.Context, *ChangeExerciseFavoriteRequest) (*ChangeExerciseFavoriteResponse, error)
	GetUserFavoriteExercises(context.Context, *GetUserFavoriteExercisesRequest) (*GetUserFavoriteExercisesResponse, error)
	GetUserStats(context.Context, *GetUserStatsRequest) (*GetUserStatsResponse, error)
	GetExerciseCollections(context.Context, *GetExerciseCollectionsRequest) (*GetExerciseCollectionsResponse, error)
	GetUserRecentExercisesChart(context.Context, *GetUserRecentExercisesChartRequest) (*GetUserRecentExercisesChartResponse, error)
}

// UnimplementedExerciseServiceServer should be embedded to have forward compatible implementations.
type UnimplementedExerciseServiceServer struct {
}

func (UnimplementedExerciseServiceServer) NewExercise(context.Context, *NewExerciseRequest) (*NewExerciseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewExercise not implemented")
}
func (UnimplementedExerciseServiceServer) AnswerExercise(context.Context, *AnswerExerciseRequest) (*AnswerExerciseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnswerExercise not implemented")
}
func (UnimplementedExerciseServiceServer) UpdateExerciseAudio(context.Context, *UpdateExerciseAudioRequest) (*UpdateExerciseAudioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExerciseAudio not implemented")
}
func (UnimplementedExerciseServiceServer) GetUserExercises(context.Context, *GetUserExercisesRequest) (*GetUserExercisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserExercises not implemented")
}
func (UnimplementedExerciseServiceServer) GetUserReadyForReviewExercises(context.Context, *GetUserReadyForReviewExercisesRequest) (*GetUserReadyForReviewExercisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserReadyForReviewExercises not implemented")
}
func (UnimplementedExerciseServiceServer) ChangeExerciseFavorite(context.Context, *ChangeExerciseFavoriteRequest) (*ChangeExerciseFavoriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeExerciseFavorite not implemented")
}
func (UnimplementedExerciseServiceServer) GetUserFavoriteExercises(context.Context, *GetUserFavoriteExercisesRequest) (*GetUserFavoriteExercisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFavoriteExercises not implemented")
}
func (UnimplementedExerciseServiceServer) GetUserStats(context.Context, *GetUserStatsRequest) (*GetUserStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserStats not implemented")
}
func (UnimplementedExerciseServiceServer) GetExerciseCollections(context.Context, *GetExerciseCollectionsRequest) (*GetExerciseCollectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExerciseCollections not implemented")
}
func (UnimplementedExerciseServiceServer) GetUserRecentExercisesChart(context.Context, *GetUserRecentExercisesChartRequest) (*GetUserRecentExercisesChartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRecentExercisesChart not implemented")
}

// UnsafeExerciseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExerciseServiceServer will
// result in compilation errors.
type UnsafeExerciseServiceServer interface {
	mustEmbedUnimplementedExerciseServiceServer()
}

func RegisterExerciseServiceServer(s grpc.ServiceRegistrar, srv ExerciseServiceServer) {
	s.RegisterService(&ExerciseService_ServiceDesc, srv)
}

func _ExerciseService_NewExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).NewExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_NewExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).NewExercise(ctx, req.(*NewExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_AnswerExercise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerExerciseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).AnswerExercise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_AnswerExercise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).AnswerExercise(ctx, req.(*AnswerExerciseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_UpdateExerciseAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExerciseAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).UpdateExerciseAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_UpdateExerciseAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).UpdateExerciseAudio(ctx, req.(*UpdateExerciseAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetUserExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserExercisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetUserExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetUserExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetUserExercises(ctx, req.(*GetUserExercisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetUserReadyForReviewExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReadyForReviewExercisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetUserReadyForReviewExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetUserReadyForReviewExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetUserReadyForReviewExercises(ctx, req.(*GetUserReadyForReviewExercisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_ChangeExerciseFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeExerciseFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).ChangeExerciseFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_ChangeExerciseFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).ChangeExerciseFavorite(ctx, req.(*ChangeExerciseFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetUserFavoriteExercises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFavoriteExercisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetUserFavoriteExercises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetUserFavoriteExercises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetUserFavoriteExercises(ctx, req.(*GetUserFavoriteExercisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetUserStats(ctx, req.(*GetUserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetExerciseCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExerciseCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetExerciseCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetExerciseCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetExerciseCollections(ctx, req.(*GetExerciseCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExerciseService_GetUserRecentExercisesChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRecentExercisesChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExerciseServiceServer).GetUserRecentExercisesChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExerciseService_GetUserRecentExercisesChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExerciseServiceServer).GetUserRecentExercisesChart(ctx, req.(*GetUserRecentExercisesChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExerciseService_ServiceDesc is the grpc.ServiceDesc for ExerciseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExerciseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exercisepb.ExerciseService",
	HandlerType: (*ExerciseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewExercise",
			Handler:    _ExerciseService_NewExercise_Handler,
		},
		{
			MethodName: "AnswerExercise",
			Handler:    _ExerciseService_AnswerExercise_Handler,
		},
		{
			MethodName: "UpdateExerciseAudio",
			Handler:    _ExerciseService_UpdateExerciseAudio_Handler,
		},
		{
			MethodName: "GetUserExercises",
			Handler:    _ExerciseService_GetUserExercises_Handler,
		},
		{
			MethodName: "GetUserReadyForReviewExercises",
			Handler:    _ExerciseService_GetUserReadyForReviewExercises_Handler,
		},
		{
			MethodName: "ChangeExerciseFavorite",
			Handler:    _ExerciseService_ChangeExerciseFavorite_Handler,
		},
		{
			MethodName: "GetUserFavoriteExercises",
			Handler:    _ExerciseService_GetUserFavoriteExercises_Handler,
		},
		{
			MethodName: "GetUserStats",
			Handler:    _ExerciseService_GetUserStats_Handler,
		},
		{
			MethodName: "GetExerciseCollections",
			Handler:    _ExerciseService_GetExerciseCollections_Handler,
		},
		{
			MethodName: "GetUserRecentExercisesChart",
			Handler:    _ExerciseService_GetUserRecentExercisesChart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exercisepb/hub.proto",
}
